
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 600000
  security:
    user:
      name: coderhouse
      password: 123
  data:
    mongodb:
      auto-index-creation: true
      database: ecommerce
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: coderhouse.camila26@gmail.com
    password: epcjbfsmnljcybnm
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
server:
  port: 8082


jwt:
  expiration: 600000
  secret: springbootjwtcoderhouse