
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 600000
  security:
    user:
      name: coderhouse
      password: 123
  data:
    mongodb:
      auto-index-creation: true
      database: ecommerce
      host: localhost
      port: 27017
server:
  port: 8082


jwt:
  expiration: 600000
  secret: springbootjwtcoderhouse